### PR TITLE
fix: sort UI readability

### LINKED ISSUE #468: chore: add small border on sort
Capture d’écran 2021-10-04 à 14 50 21

Mais vraiment pas agressive

### PR DESCRIPTION
**Pull request by lucienklein**
image

### CODE REVIEW

File: admin/src/components/list/index.js [hunk 1]
```diff
@@ -109,19 +109,26 @@ export const ResultTable = styled.div`
...
+    margin-right: 2rem;
     position: absolute;
     top: 0.5rem;
     left: 0.5rem;
     outline: 0;
-    background-color: #fff;
+    background-color: #f7fafc;
     box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.05);
     border: 0;
     border-radius: 6px;
```
Comment (rap2hpoutre) [inline admin/src/components/list/index.js]: You forgot to remove the existing `border` and `border-radius` properties (so it's erased).
I guess we could remove: 

```
border: 0;
border-radius: 6px;
```

Or maybe about `border-radius` keep the `border-radius: 6px;` and remove `border-radius: 2px;`

File: admin/src/components/list/index.js [hunk 2]
```diff
@@ -109,19 +109,26 @@ export const ResultTable = styled.div`
     }
   }
   select.sort-options {
-    background: none; // remove the arrows added by sortOptions
+    background: transparent;
+    background-image: url("data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 10l5 5 5-5z'/><path d='M0 0h24v24H0z' fill='none'/></svg>");
+    background-repeat: no-repeat;
+    background-position-x: 100%;
+    background-position-y: 5px;
```
Comment (rap2hpoutre) [inline admin/src/components/list/index.js:116]: 3 seems better

```suggestion
    background-position-y: 3px;
```
Capture d’écran 2021-10-07 à 15 49 54

**Review by rap2hpoutre — COMMENTED** [review]
Cool 👍 
Fais ce que tu veux/peux avec mes suggestions et renvoie moi :)

**Review by rap2hpoutre — APPROVED** [review]

**Review by rap2hpoutre — APPROVED** [review]
👏 👏 👏   

Tu peux squash+merge !
